controllers:
# Default Symfony default controllers dir
    resource: ../../src/Controller/
# Custome default controllers dir
    # resource: ../../src/Pfm/Infrastructure/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
